version: "2"
run:
  relative-path-mode: gitroot
  modules-download-mode: readonly
output:
  path-mode: "abs"
severity:
  default: error
formatters:
  enable:
    - gci
    - goimports
linters:
  default: none
  enable:
    - govet
    - gosec
    - errcheck
    - wrapcheck
    - unused
    - nakedret
    - mnd
    - interfacebloat
    - exhaustive
    - exhaustruct
    - errchkjson
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - wsl_v5
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - paralleltest
  settings:
    wrapcheck:
      ignore-package-globs:
        - context
        - github.com/WinPooh32/reviewpls/internal/retry
    testifylint:
      disable:
        - require-error
    exhaustruct:
      exclude:
        - ^github.com/openai/openai-go/v2.*
